name: pscis_env
channels:
  - esri
  - anaconda
  - defaults
dependencies:
  - python=3.11
  - arcgis
  - python-dotenv
  - pip
  - pip:
    - "--editable=git+https://github.com/taralyh/pscis.git#egg=survey_to_esf"
